# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7a60d23e5c0d149a174f155ba5520d8e035db1828fc19833e57fe1bdbd9a00e27f3dc089f72aa614a3619ae05207d4959ff3edb31a1f9591945d327342bfefb

test:
  secret_key_base: 6fbd07ba4edeae75fc3431a07d5c71232c579f3ef43c8a2043665cfd5934163eabc11ff865fe363b99bb99ff83b54a7e76a269c5179b04eb55cf4cef5105fc15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
